linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: -1
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
  gocyclo:
    min-complexity: 15
  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
  mnd:
    # don't include the "operation" and "assign"
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '3'
    ignored-functions:
      - strings.SplitN
  lll:
    line-length: 140
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true
  revive:
    rules:
      - name: unexported-return
        disabled: true
      - name: unused-parameter

linters:
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - intrange
    - ineffassign
    - lll
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace

run:
  timeout: 5m
