services:
  dev:
    container_name: access_control_explorer_dev
    build:
      context: docker/dev
    platform: linux/amd64
    volumes:
      - './:/usr/code'
    working_dir: '/usr/code'
    env_file:
      - .env
    command: [ '/bin/sh', '-c', 'sleep infinity' ]
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgres

  postgres:
    container_name: access_control_explorer_postgres
    image: postgres:17.4-bookworm
    volumes:
      - ./docker/postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
      POSTGRES_DB_DEMO: ${POSTGRES_DB_DEMO:-demo_db}
      POSTGRES_DB_TEST: ${POSTGRES_DB_TEST:-test_db}
    restart: always
    ports:
      - "5432:5432"
